apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: bookmarks-app
spec:
  targetNamespace: staging
  values:
    frontend:
      replicas: 1
      ingress:
        hosts:
          - host: app.staging.local
            paths:
              - path: /
                pathType: ImplementationSpecific
      env:
        VITE_API_BASE_URL: "http://api.staging.local"
    backend:
      replicas: 1
      image:
        tag: "sha-20b0091"
      database:
        secretName: bookmarks-staging-db-app
        secretKey: uri
      ingress:
        hosts:
          - host: api.staging.local
            paths:
              - path: /
                pathType: ImplementationSpecific
