apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: prod-db-migration
  namespace: flux-system
spec:
  dependsOn:
    - name: prod-db
  interval: 10m
  path: ./infrastructure/migrations/production
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
