apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - flux-system
  - namespaces-flux-kustomization.yaml
  - cnpg-flux-kustomization.yaml
  - ingress-nginx-flux-kustomization.yaml
  - production/db.yaml
  - production/db-migration.yaml
  - production/app.yaml
  - staging/db.yaml
  - staging/db-migration.yaml
  - staging/app.yaml
