apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bookmarks-app.backendFullname" . }}
  labels:
    {{- include "bookmarks-app.backendLabels" . | nindent 4 }}
spec:
  {{- if not .Values.backend.autoscaling.enabled }}
  replicas: {{ .Values.backend.replicas }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "bookmarks-app.backendSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "bookmarks-app.backendLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "bookmarks-app.serviceAccountName" . }}
      containers:
        - name: {{ .Values.backend.containerName }}
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - name: {{ .Values.backend.service.targetName }}
              containerPort: {{ .Values.backend.service.port }}
              protocol: TCP
          env:
            - name: PORT
              value: {{ .Values.backend.env.PORT | quote }}
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.backend.database.secretName }}
                  key: {{ .Values.backend.database.secretKey }}
          {{- with .Values.backend.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.backend.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.backend.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
