apiVersion: v1
kind: Service
metadata:
  name: {{ include "bookmarks-app.backendFullname" . }}
  labels:
    {{- include "bookmarks-app.backendLabels" . | nindent 4 }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.targetName }}
      protocol: TCP
      name: http
  selector:
    {{- include "bookmarks-app.backendSelectorLabels" . | nindent 4 }}
