apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bookmarks-app.frontendFullname" . }}
  labels:
    {{- include "bookmarks-app.frontendLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      {{- include "bookmarks-app.frontendSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "bookmarks-app.frontendLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "bookmarks-app.serviceAccountName" . }}
      containers:
        - name: {{ .Values.frontend.containerName }}
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - name: {{ .Values.frontend.service.targetName }}
              containerPort: {{ .Values.frontend.service.port }}
              protocol: TCP
          env:
            - name: VITE_API_BASE_URL
              value: {{ .Values.frontend.env.VITE_API_BASE_URL | quote }}
          {{- with .Values.frontend.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.frontend.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.frontend.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
