apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: bookmarks-app
spec:
  interval: 10m
  releaseName: bookmarks-app
  driftDetection:
    mode: enabled

  chart:
    spec:
      chart: ./charts/bookmarks-app
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 10m

  install:
    createNamespace: true
    remediation:
      retries: 3

  upgrade:
    remediation:
      retries: 3
