apiVersion: batch/v1
kind: Job
metadata:
  name: bookmarks-db-migration-001
  namespace: staging
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: migrate
          image: iphilippenko/bookmarks-app-server:2.0.0
          imagePullPolicy: IfNotPresent
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: bookmarks-staging-db-app
                  key: uri
          command:
            - npm
            - run
            - migrate
            - --workspace
            - server
